name: 'package'
on:
  push:
    branches: ['*']

permissions:
  packages: 'write'

jobs:
  docker:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'

      - uses: 'docker/setup-buildx-action@v3'
      - uses: 'docker/login-action@v3'
        with:
          registry: 'ghcr.io'
          username: '${{ github.repository_owner }}'
          password: '${{ secrets.GITHUB_TOKEN }}'

      - uses: 'docker/build-push-action@v6'
        if: github.ref_name == 'main'
        with:
          context: '.'
          push:    true
          tags:    'ghcr.io/occrp/alfred-elasticsearch:${{ github.sha }}'
          platforms: 'darwin/amd64,linux/arm64,linux/amd64'

      - uses: 'docker/build-push-action@v6'
        if: github.ref_name != 'main'
        with:
          context: '.'
          push:    true
          tags:    'ghcr.io/occrp/alfred-elasticsearch:${{ github.ref_name }}-${{ github.sha }}'
          platforms: 'darwin/arm64,linux/arm64,linux/amd64'
